---
    name: Test
    on:
      pull_request:
        branches:
          - main
    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 20
          - name: Run custom action
            uses: ./
          - name: Run custom action with input
            uses: ./
            with:
              person: Batman
    
    
          